---
title: "Plotly Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# library packages and read in the data
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r, include = FALSE}
data(instacart)

instacart <- 
  instacart %>%
  janitor::clean_names() %>% 
  select(
    add_to_cart_order, reordered, user_id, order_dow, order_hour_of_day, days_since_prior_order, product_name, aisle, department)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Product Average Order Interval Time Distribution in Different Aisle in Produce Department

```{r}
instacart %>% 
  select(days_since_prior_order, product_name, aisle, department) %>% 
  filter(department == "produce") %>% 
  group_by(product_name) %>% 
  summarize(interval_time = mean(days_since_prior_order), aisle) %>% 
  distinct() %>% 
  plot_ly(y = ~interval_time, color = ~aisle, type = "box", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Mean Order Hour in A Day by Different Product in Snacks Department

```{r}
instacart %>% 
  select(order_hour_of_day, product_name, aisle, department) %>% 
  filter(department == "snacks") %>% 
  group_by(product_name) %>% 
  summarize(mean_order_hour = mean(order_hour_of_day), product_name, aisle) %>% 
  distinct() %>% 
  plot_ly(x = ~product_name, y = ~mean_order_hour, color = ~aisle, type = "bar", colors = "viridis")
```

### Order Interval Time V.S. Mean Order Hour by Product in A Day in Different Aisle in Frozen Department

```{r}
instacart %>% 
  select(days_since_prior_order, order_hour_of_day, product_name, aisle, department) %>% 
  filter(department == "frozen") %>% 
  group_by(product_name) %>% 
  summarize(interval_time = mean(days_since_prior_order), mean_order_hour = mean(order_hour_of_day), product_name, aisle) %>% 
  distinct() %>% 
  plot_ly(x = ~mean_order_hour, y = ~interval_time, color = ~aisle, type = "scatter", colors = "viridis", alpha = 0.5)
```



